a = input('digite algo:')
print('o tipo primitivo é', type(a))
print('é um numero?', a. isnumeric())
print('So tem espaços?', a. isspace() )
print('é um numero?', a.isnumeric())
print('é alfabeto?', a. isalpha())
print('é alfanumérico?', a. isalnum())
print('esta em minusculas?', a. isupper())
print('esta em maiusculas?', a. istitle())
print('esta capitalizada?', a. istitle())